version: 2

models:
  - name: dim_listings_clean
    columns:

      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_clean')
              field: host_id

      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      # generic test for checking minimum nights column. Check positive_value.sql
      # in macros folder
      - name: minimum_nights
        tests:
          - positive_value
      
  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

          # this test checks that 99% values in price column are between 50 and 500
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
            
          # this test states that max value for price shouldbe between 5k and 09k
          # We can also specify a min_value, the max value was 8k in DWH
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 5000
              max_value: 9000
              # the severity can be added for any test
              config:
                severity: warn